package cn.edu.xmu.privilege.mapper;

import cn.edu.xmu.privilege.model.po.UserProxyPo;
import cn.edu.xmu.privilege.model.po.UserProxyPoExample;
import java.util.List;

public interface UserProxyPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int insert(UserProxyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int insertSelective(UserProxyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    List<UserProxyPo> selectByExample(UserProxyPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    UserProxyPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserProxyPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_proxy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserProxyPo record);
}