package cn.edu.xmu.timer.mapper;

import cn.edu.xmu.timer.model.po.TaskPo;
import cn.edu.xmu.timer.model.po.TaskPoExample;
import java.util.List;

public interface TaskPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    int deleteByExample(TaskPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    int insert(TaskPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    int insertSelective(TaskPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    List<TaskPo> selectByExample(TaskPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    TaskPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskPo record);

}