package cn.edu.xmu.log.model.po;

import java.time.LocalDateTime;

public class LogPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.descr
     *
     * @mbg.generated
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.privilege_id
     *
     * @mbg.generated
     */
    private Long privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.success
     *
     * @mbg.generated
     */
    private Byte success;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_log.depart_id
     *
     * @mbg.generated
     */
    private Long departId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.id
     *
     * @return the value of auth_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.id
     *
     * @param id the value for auth_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.user_id
     *
     * @return the value of auth_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.user_id
     *
     * @param userId the value for auth_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.ip
     *
     * @return the value of auth_log.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.ip
     *
     * @param ip the value for auth_log.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.descr
     *
     * @return the value of auth_log.descr
     *
     * @mbg.generated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.descr
     *
     * @param descr the value for auth_log.descr
     *
     * @mbg.generated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.privilege_id
     *
     * @return the value of auth_log.privilege_id
     *
     * @mbg.generated
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.privilege_id
     *
     * @param privilegeId the value for auth_log.privilege_id
     *
     * @mbg.generated
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.success
     *
     * @return the value of auth_log.success
     *
     * @mbg.generated
     */
    public Byte getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.success
     *
     * @param success the value for auth_log.success
     *
     * @mbg.generated
     */
    public void setSuccess(Byte success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.gmt_create
     *
     * @return the value of auth_log.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.gmt_create
     *
     * @param gmtCreate the value for auth_log.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_log.depart_id
     *
     * @return the value of auth_log.depart_id
     *
     * @mbg.generated
     */
    public Long getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_log.depart_id
     *
     * @param departId the value for auth_log.depart_id
     *
     * @mbg.generated
     */
    public void setDepartId(Long departId) {
        this.departId = departId;
    }
}